name: 'Playwright Last Failed'
description:
  'The action helps to run last failed Playwright tests using Currents cache'
author: 'Currents Software Inc'

inputs:
  key:
    description: 'Your secret Record Key obtained from Currents'
    required: false
    default: ''
  debug:
    description: 'Enable debug logging'
    required: false
    default: 'false'
  id:
    description: 'The ID the data is saved under in the cache'
    required: false
    default: ''
  path:
    description: 'Comma-separated list of paths to cache'
    required: false
    default: ''
  output-dir:
    description: 'Path to the directory where output will be written'
    required: false
    default: ''
  pw-output-dir:
    description: 'Directory for artifacts produced by Playwright tests'
    required: false
    default: 'test-results'
  matrix-index:
    description: 'The index of the matrix to use'
    required: false
    default: '1'
  matrix-total:
    description: 'The total number of matrices available'
    required: false
    default: '1'
  use-api:
    description: 'Use Currents API for obtaining the list of failed tests'
    required: false
    default: 'false'
  or8n:
    description: 'Enable or8n integration'
    required: false
    default: 'false'
  api-key:
    description: 'Your secret API Key obtained from Currents dashboard'
    required: false
    default: ''
  project-id:
    description: 'Project ID obtained from Currents dashboard'
    required: false
    default: ''
  previous-ci-build-id:
    description: 'The ID of the previous CI build'
    required: false
    default: ''

outputs:
  extra-pw-flags:
    description: "Extra flags to pass to Playwright's test runner"

runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
